### ISSUE TITLE
cargo test fails

### ISSUE THREAD

**Issue by caulagi** [brson/httptest#6]
`cargo test` fails for me with this error -

``` bash
running 2 tests
test post_backend ... FAILED
test get_backend ... FAILED

failures:

---- post_backend stdout ----
    thread 'post_backend' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 61, message: "Connection refused" } })', ../src/libcore/result.rs:785

---- get_backend stdout ----
    thread 'get_backend' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 61, message: "Connection refused" } })', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Am I missing something?  I am running rustup with stable channel -

```
$ cargo -V
cargo 0.11.0-nightly (259324c 2016-05-20)
$ rustc -V
rustc 1.10.0 (cfcb716cf 2016-07-03)
```

**Comment by brson** [comment]
It looks to me like the test cases are both bogus. They expect a server to exist that they don't set up on their own. They could just be deleted. Thanks for the report!
